name: taski
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-183.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  hive_generator: ^1.1.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400

        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500

        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
